### ISSUE TITLE
Docs never seem to be able to deploy on Documenter 1.0

### ISSUE THREAD

**Issue by DanielVandH** [julia-actions/julia-docdeploy#31]
I'm copypasting an issue from https://github.com/JuliaDocs/Documenter.jl/issues/2264, since it seems like it might be more related to this action.

> In https://github.com/DanielVandH/FiniteVolumeMethod.jl/pull/50, I'm testing the deployment with Documenter v1 vs. Documenter v0.27. In the v0.27 case [here](https://github.com/DanielVandH/FiniteVolumeMethod.jl/actions/runs/6207291546/job/16852393497), everything runs fine. In the v1 case [here](https://github.com/DanielVandH/FiniteVolumeMethod.jl/actions/runs/6213368725/job/16864357366?pr=50), it just never finishes. I don't think this is a fluke either, since I also noticed it a lot in a previous PR ([this one](https://github.com/DanielVandH/FiniteVolumeMethod.jl/pull/49), but I made pr50 to show this issue since there's too many commits in pr49).
> 
> Is there anything particular about the make.jl file that would be causing this in v1 versus v0.27? The make.jl is here https://github.com/DanielVandH/FiniteVolumeMethod.jl/blob/doc/docs/make.jl

A relevant reply from @mortenpi: 

> Then I would move the issue there and use the standard setup in the meanwhile. It does not look like a Documenter bug. Nothing specifically stands out though. It looks like it's stuck in this function somehow: https://github.com/JuliaDocs/Documenter.jl/blob/c3fc63b108feacf222e5ab98b1fb88231dc995a0/src/documents.jl#L905-L913
> 
> My best guess would be that it's the loading of GitHubActions.jl from a different environment brings in conflicting dependencies, and that just creates some weird behavior. But I am not entirely convinced of that either.

_Originally posted by @mortenpi in https://github.com/JuliaDocs/Documenter.jl/issues/2264#issuecomment-1722604980_

Any ideas on what might be happening based on those logs ((https://github.com/DanielVandH/FiniteVolumeMethod.jl/actions/runs/6213368725/job/16864357366?pr=50)? I'm not sure how to properly debug with this action directly locally.

**Comment by mofeing** [comment]
Same happens to me in https://github.com/bsc-quantic/Tenet.jl/actions/runs/6215787902/job/16869026625

Docs DO deploy but time increased from 20min to 2h!

**Comment by ericphanson** [comment]
I wonder if it could be https://github.com/JuliaDocs/MarkdownAST.jl/blob/99e0f82c1e3cc16c862cd3636936e3bcb6591a42/src/node.jl#L118, if we are generating/logging tons and tons of stacktraces. Since the main thing docdeploy does differently is it setups up a GHA compatible logger so that doctest failures will show up as annotations on the PR. And I believe Documenter v1 is the first version w/ that code running. Also, looking at the code, I think GitHubActionsLogger doesn't filter based on loglevel, and instead leaves that up to GHA. So if there is super duper verbose debug logging, we are passing it out to GHA and leaving it to them to filter; maybe that is slow? (Or the stacktrace calls, if indeed Documenter is doing tons of them?)

I don't think it is a dependency issue, as GHA only depends on JSON v0.21, and Documenter also depends on JSON and allows v0.21 as the latest compatible release.

**Comment by ericphanson** [comment]
I think https://github.com/julia-actions/GitHubActions.jl/pull/33 may have fixed the issue. If anyone experience this can try again and let me know, that would be helpful!

**Comment by DanielVandH** [comment]
Yes, seems to have worked @ericphanson! The CI completed in the expected time https://github.com/DanielVandH/FiniteVolumeMethod.jl/pull/50. This can be closed then I believe, unless @mofeing doesn't also see the same improvements?

**Comment by mofeing** [comment]
I've just tried it and can confirm that documentation has returned back to normal times.
Thanks @ericphanson!
